export default {
  id: "kimchi",
  priority: 25,
  alias: "ki",
  uiAlias: "ki",
  display: {
    name: "Kimchi",
    icon: "local_dining",
    color: "#FF6B35",
    textIcon: "KC",
    website: "https://kimchi.dev",
    notice: {
      apiKeyUrl: "https://app.kimchi.dev/settings",
    },
  },
  category: "freeTier",
  authType: "apikey",
  hasOAuth: false,
  authModes: ["apikey"],
  serviceKinds: ["llm", "webSearch"],
  searchConfig: {
    baseUrl: "https://llm.kimchi.dev/v1/search",
    authType: "apikey",
    authHeader: "bearer",
    format: "openai",
    timeoutMs: 25000,
  },
  transport: {
    baseUrl: "https://llm.kimchi.dev/openai/v1/chat/completions",
    format: "openai",
    timeoutMs: 20000,
    headers: {
      "User-Agent": "kimchi/0.1.39",
      Accept: "application/json;q=1, text/event-stream;q=0",
    },
    auth: {
      apiKey: {
        header: "Authorization",
        scheme: "bearer",
        hooks: ["kimchiHeaders"],
      },
    },
    forceStream: false,
    preserveAccept: true,
    retry: {
      429: { attempts: 3, delayMs: 500 },
      502: { attempts: 3, delayMs: 500 },
      503: { attempts: 3, delayMs: 1000 },
    },
  },
  models: [
    {
      id: "kimi-k2.7",
      name: "Kimi K2.7",
      capabilities: { reasoning: false },
      contextWindow: 256000,
      maxOutput: 32000,
    },
    {
      id: "kimi-k2.6",
      name: "Kimi K2.6",
      capabilities: { reasoning: false },
      contextWindow: 262144,
      maxOutput: 32768,
    },
    {
      id: "kimi-k2.5",
      name: "Kimi K2.5",
      capabilities: { reasoning: false },
      contextWindow: 164000,
      maxOutput: 32000,
    },
    {
      id: "minimax-m3",
      name: "MiniMax M3",
      capabilities: { reasoning: false },
      contextWindow: 196608,
      maxOutput: 32768,
    },
    {
      id: "minimax-m2.7",
      name: "MiniMax M2.7",
      capabilities: { reasoning: false },
      contextWindow: 200000,
      maxOutput: 32000,
    },
    {
      id: "minimax-m2.5",
      name: "MiniMax M2.5",
      capabilities: { reasoning: false },
      contextWindow: 200000,
      maxOutput: 32000,
    },
    {
      id: "nemotron-3-ultra-fp4",
      name: "Nemotron 3 Ultra FP4",
      capabilities: { reasoning: false },
      contextWindow: 128000,
      maxOutput: 8192,
    },
    {
      id: "nemotron-3-super-fp4",
      name: "Nemotron 3 Super FP4",
      capabilities: { reasoning: false },
      contextWindow: 128000,
      maxOutput: 8192,
    },
    {
      id: "qwen3-coder-next-fp8",
      name: "Qwen3 Coder Next FP8",
      capabilities: { reasoning: false },
      contextWindow: 262144,
      maxOutput: 32768,
    },
    {
      id: "smollm2-360m",
      name: "SmolLM2 360M",
      capabilities: { reasoning: false },
      contextWindow: 8192,
      maxOutput: 4096,
    },
    {
      id: "smollm2-135m",
      name: "SmolLM2 135M",
      capabilities: { reasoning: false },
      contextWindow: 8192,
      maxOutput: 4096,
    },
  ],
};
